<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.13">
  <compounddef id="classpal_1_1InternalException_1_1Full" kind="class" language="C++" prot="public">
    <compoundname>pal::InternalException::Full</compoundname>
    <basecompoundref prot="public" virt="non-virtual">exception</basecompoundref>
    <includes refid="internalexception_8h" local="no">internalexception.h</includes>
      <sectiondef kind="private-func">
      <memberdef kind="function" id="classpal_1_1InternalException_1_1Full_1a2b92709122484ce18d04a96fd26f259f" prot="private" static="no" const="yes" explicit="no" inline="yes" virt="non-virtual">
        <type>const char *</type>
        <definition>const char* pal::InternalException::Full::what</definition>
        <argsstring>() const override</argsstring>
        <name>what</name>
        <exceptions> throw ()</exceptions>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="/home/suricactus/work/qgis/QGIS/src/core/pal/internalexception.h" line="52" column="1" bodyfile="/home/suricactus/work/qgis/QGIS/src/core/pal/internalexception.h" bodystart="52" bodyend="55"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
<para>Thrown when something is added in a <ref refid="classpal_1_1InternalException_1_1Full" kindref="compound">Full</ref> set. </para>    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="435">
        <label>exception</label>
      </node>
      <node id="434">
        <label>pal::InternalException::Full</label>
        <link refid="classpal_1_1InternalException_1_1Full"/>
        <childnode refid="435" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="437">
        <label>exception</label>
      </node>
      <node id="436">
        <label>pal::InternalException::Full</label>
        <link refid="classpal_1_1InternalException_1_1Full"/>
        <childnode refid="437" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="/home/suricactus/work/qgis/QGIS/src/core/pal/internalexception.h" line="51" column="1" bodyfile="/home/suricactus/work/qgis/QGIS/src/core/pal/internalexception.h" bodystart="50" bodyend="56"/>
    <listofallmembers>
      <member refid="classpal_1_1InternalException_1_1Full_1a2b92709122484ce18d04a96fd26f259f" prot="private" virt="non-virtual"><scope>pal::InternalException::Full</scope><name>what</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
